version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.back
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    container_name: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    container_name: frontend

networks:
  app-network:
    driver: bridge
